baseURL: "https://rodneymaiato.dev"
languageCode: en-us
title: Rodney Maiato
theme: PaperMod
enableInlineShortcodes: true

googleAnalytics: G-4Q4P648RX1

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  homeInfoParams:
      Title: Welcome! 
      Content: This is where I write about coding and decoding 

  socialIcons: # optional
      - name: "Twitter"
        url: "https://twitter.com/rodmaiato"
      - name: "Github"
        url: "https://github.com/rodneymaiato"
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true



menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: about
      name: about
      url: /about/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 15
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true
